#!/usr/bin/env node

var http = require('http');
var fortitude = require('./fortitude');

// initialize the fortitude express app
var app = fortitude();

var server = http.createServer(app);

var port = parseInt(process.env.FORTITUDE_PORT || '3005');

server.listen(port);

server.on('error', function(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(port + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(port + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
});

server.on('listening', function() {
  console.log('Listening on port ' + port);
});


